server:
  port: 18082
spring:
  application:
    name: canal
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
    instance:
      prefer-ip-address: true
feign:
  hystrix: true
hystrix:
  command:
    defualt:
      execution:
        timeout:
          enable: true
        isolation:
          strategy: SEMAPHORE
canal:
  client:
    instances:
      example:
        host: 192.168.20.50
        port: 11111
        batchSize: 1000